name = "earthapp-crust"
compatibility_date = "2025-06-20"
main = ".output/server/index.mjs"
routes = [
    { pattern = "app.earth-app.com", custom_domain = true }
]
send_metrics = false

[observability]
enabled = true
head_sampling_rate = 0.1
