name = "earthapp-crust"
compatibility_date = "2025-06-20"
main = ".output/server/index.mjs"
assets = { directory = ".output/public" }
routes = [
    { pattern = "app.earth-app.com", custom_domain = true }
]

[observability]
enabled = true
head_sampling_rate = 0.1